#!/bin/bash
echo "🚀 Vercel Environment Variables Setup"
echo ""
echo "Run these commands to add your environment variables:"
echo ""
echo "vercel env add TWILIO_ACCOUNT_SID production"
echo "  Paste: ACbe4fe93cad91172d1836bf0b1df21f9c"
echo ""
echo "vercel env add TWILIO_AUTH_TOKEN production"
echo "  Paste: 1af3b81750c6c09db04a9fc5bac6493a"
echo ""
echo "vercel env add TWILIO_WHATSAPP_NUMBER production"
echo "  Paste: whatsapp:+14155238886"
echo ""
echo "vercel env add ADMIN_WHATSAPP production"
echo "  Paste: +15088826327"
echo ""
echo "vercel env add ENCRYPTION_KEY production"
echo "  Paste: smlXM3dWJxtHgwbYKOYNXMrzfezupZT1"
echo ""
echo "vercel env add TZ production"
echo "  Paste: Australia/Perth"
echo ""
echo "⚠️  Get NEW Supabase keys from:"
echo "https://supabase.com/dashboard/project/qmedckkwtgkhrdihqrnd/settings/api"
